# Persistence configuration
persistence true
persistence_location /mosquitto/data/

# Logging
log_dest file /mosquitto/log/mosquitto.log

# Network

# Default MQTT port
listener 1883

# Authentication
# NOTE: Enabled for local/dev environments only.
# In production, this must be disabled and replaced by proper authentication.
allow_anonymous true
