# Generated by Django 6.0.1 on 2026-01-15 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('ideal_cycle_time', models.FloatField(default=10.0, help_text='In seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CYCLE', 'Production Cycle'), ('ERROR_START', 'Downtime Start'), ('ERROR_END', 'Downtime End')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.machine')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['machine', 'timestamp'], name='core_produc_machine_76b3ef_idx')],
            },
        ),
    ]
