# Generated by Django 6.0.1 on 2026-01-17 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('current_amps', models.FloatField(help_text='Corrente do Motor em Amperes')),
            ],
        ),
        migrations.AlterModelOptions(
            name='productionevent',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='productionevent',
            name='core_produc_machine_76b3ef_idx',
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(default='generic', max_length=50),
        ),
        migrations.AlterField(
            model_name='machine',
            name='device_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='ideal_cycle_time',
            field=models.FloatField(default=10.0),
        ),
        migrations.AlterField(
            model_name='productionevent',
            name='event_type',
            field=models.CharField(choices=[('CYCLE', 'Peça Boa'), ('SCRAP', 'Refugo/Peça Ruim'), ('ERROR_START', 'Início Parada'), ('ERROR_END', 'Fim Parada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productionevent',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.machine'),
        ),
    ]
