# Generated by Django 6.0.1 on 2026-01-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sensorreading_alter_productionevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='machines/'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='device_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(default='Genérica', max_length=50),
        ),
    ]
