# Generated by Django 6.0.1 on 2026-01-21 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_machine_description_machine_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.FloatField(default=0.0)),
                ('performance', models.FloatField(default=0.0)),
                ('quality', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oee', to='core.machine')),
            ],
        ),
    ]
